//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04_06_dist
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authentication
    {
        public int ID { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Type_of_login_id { get; set; }
        public int Employee_id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Type_of_login Type_of_login { get; set; }
    }
}
