//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04_06_dist
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Service
    {
        public int ID { get; set; }
        public Nullable<int> Order_id { get; set; }
        public Nullable<int> Service_id { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Service Service { get; set; }
    }
}
