//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04_06_dist
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Service = new HashSet<Order_Service>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date_of_creation { get; set; }
        public System.TimeSpan Time_of_order { get; set; }
        public int Code_client { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> Date_of_close { get; set; }
        public int Time_of_rental { get; set; }
        public int Employee_id { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Service> Order_Service { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
